project: 
  type: book
  preview: 
      port: 5678
  execute-dir: project

lang: de

format: 
  html:
    theme:
      dark: [darkly, custom-dark.scss]
      light: [flatly, custom-light.scss]
    css: 
      - custom.css
      - theme-custom.scss
      #- presenter-mode.css
    bibliography: bibliography.bib
    number-sections: false
    code-tools:
      source: false

execute:
  freeze: true
  error: true
  message: false
  warning: false
    
book:
  title: "Research Methods HS22"
  sidebar: 
    logo: images/zhaw_sw_neg.png
    collapse-level: 1
    style: floating
  reader-mode: true    
  chapters:
    - index.qmd
    - part: PrePro.qmd
      chapters:
      - prepro/Prepro1_Demo.qmd
      - prepro/Prepro1_Uebung.qmd
      - --
      - prepro/Prepro2_Demo.qmd
      - prepro/Prepro2_Uebung_A.qmd
      - prepro/Prepro2_Uebung_B.qmd
      - --
      - prepro/Prepro3_Demo.qmd
      - prepro/Prepro3_Uebung.qmd
    - part: InfoVis.qmd
      chapters:
      - infovis/Infovis1_Demo.qmd
      - infovis/Infovis1_Script_eda.qmd
      - infovis/Infovis1_Uebung.qmd
      - --
      - infovis/Infovis2_Uebung_A.qmd
      - infovis/Infovis2_Uebung_B.qmd
    - part: Stat1-4.qmd
      chapters:
      - stat1-4/Statistik1_Demo.qmd
      - stat1-4/Statistik1_Novanimal.qmd
      - stat1-4/Statistik1_Uebung.qmd
      - stat1-4/Statistik1_Loesung.qmd
      - --
      - stat1-4/Statistik2_Demo.qmd
      - stat1-4/Statistik2_Uebung.qmd
      - stat1-4/Statistik2_Loesung_Beispiel.qmd
      - stat1-4/Statistik2_Loesung_1.qmd
      - stat1-4/Statistik2_Loesung_2223s.qmd
      - stat1-4/Statistik2_Loesung_23n.qmd
      - --
      - stat1-4/Statistik3_Demo.qmd
      - stat1-4/Statistik3_Uebung.qmd
      - stat1-4/Statistik3_Loesung.qmd      
      - --
      - stat1-4/Statistik4_Demo.qmd
      - stat1-4/Statistik4_Uebung.qmd      
      - stat1-4/Statistik4_Loesung_1.qmd
      - stat1-4/Statistik4_Loesung_2n.qmd
      - stat1-4/Statistik4_Loesung_2s.qmd
    - part: Stat5-8.qmd
      chapters:
      - stat5-8/Statistik5_Demo.qmd
      - stat5-8/Statistik5_Uebung.qmd      
      - stat5-8/Statistik5_Loesung_1.qmd
      - stat5-8/Statistik5_Loesung_2.qmd
      - --
      - stat5-8/Statistik6_Demo.qmd
      - stat5-8/Statistik6_Uebung.qmd      
      - stat5-8/Statistik6_Loesung.qmd
      - --
      - stat5-8/Statistik7_Demo.qmd
      - stat5-8/Statistik7_Uebung.qmd      
      - stat5-8/Statistik7_Loesung.qmd
      - --
      - stat5-8/Statistik8_Demo.qmd
      - stat5-8/Statistik8_Uebung.qmd      
      - stat5-8/Statistik8_Loesung.qmd
    - part: StatKons.qmd
      chapters:
      - statKons/StatKons1_Demo_assoziationen.qmd
      - statKons/StatKons1_Demo_open_datasets.qmd
      #- statKons/StatKons1_Demo_suggest_datasets.qmd
      - --
      - statKons/StatKons2_Demo_PCA.qmd
      - --
      - statKons/StatKons3_Demo_LM.qmd
      - --
      - statKons/StatKons4_Demo_GLM.qmd
    - part: RaumAn.qmd
      chapters:
      - rauman/Rauman1_Uebung_A.qmd
      - rauman/Rauman1_Uebung_B.qmd
      - --
      - rauman/Rauman2_Uebung_A.qmd
      - rauman/Rauman2_Uebung_B.qmd
      - rauman/Rauman2_Uebung_C.qmd
      - --
      - rauman/Rauman3_Uebung_A.qmd
      - --
      - rauman/Rauman4_Uebung_A.qmd
      - rauman/Rauman4_Uebung_B.qmd
      - --
      - rauman/Rauman5_Uebung_A.qmd 
      - rauman/Rauman5_Uebung_B.qmd 
    - part: "Fallstudie S"
      chapters:
      - fallstudie_s/1_Einleitung.qmd
      - fallstudie_s/2_Felderhebung.qmd
      # - --
      - fallstudie_s/3_Aufgabenstellung.qmd
      # - --
      - fallstudie_s/4_Projektierung.qmd
      - fallstudie_s/5_Vorverarbeitung_Uebung.qmd
      - fallstudie_s/5_Vorverarbeitung_Loesung.qmd
      - fallstudie_s/6_Deskr_Analysen_Uebung.qmd
      - fallstudie_s/6_Deskr_Analysen_Loesung.qmd
      - fallstudie_s/7_Multivariat_Uebung.qmd
      - fallstudie_s/7_Multivariat_Loesung.qmd
    - part: "Fallstudie N"
      chapters:
      - fallstudie_n/1_Vorbemerkung.qmd
      - --
      - fallstudie_n/2_Datenverarbeitung_Uebung.qmd
      - fallstudie_n/2_Datenverarbeitung_Loesung.qmd
      - --
      - fallstudie_n/3_Berechnung_Homeranges_Uebung.qmd
      - fallstudie_n/3_Berechnung_Homeranges_Loesung.qmd
      - --
      - fallstudie_n/4_Multivariate_Modelle_Uebung.qmd
      - fallstudie_n/4_Multivariate_Modelle_Loesung.qmd
      - -- 
      - fallstudie_n/5_Variablenselektion_Uebung.qmd
      - fallstudie_n/5_Variablenselektion_Loesung.qmd
      - --
      - fallstudie_n/6_Guete_und_Diagnostics_Uebung.qmd
      - fallstudie_n/6_Guete_und_Diagnostics_Loesung.qmd
      #- --
      #- fallstudie_n/7_Modelle_mit_Nutzungsintensitaet.qmd
    - part: "Anhang"
      chapters:
      - References.qmd