---
date: 2022-11-08
lesson: Stat4
thema: Komplexere Regressionsmethoden
index: 2
---

# Stat4: Übung

##	Aufgabe 4.1: Nicht-lineare Regression

**Datensatz [Curonian_Spit.csv](https://moodle.zhaw.ch/mod/resource/view.php?id=606569)**

Dieser enthält gemittelte Pflanzenartenzahlen (Species.richness) von
geschachtelten Plots (Vegetationsaufnahmen) der Pflanzengesellschaft LolioCynosuretum im Nationalpark Kurische Nehrung (Russland) auf
Flächengrössen (Area) von 0.0001 bis 900 m².

**Ermittelt den funktionellen Zusammenhang (das beste Modell), der die Zunahme der Artenzahl mit der Flächengrösse am besten beschreibt.Berücksichtigt dabei mindestens die Potenzfunktion (power function, die logarithmische Funktion (logarithmic function,und eine Funktion mit Sättigung (saturation, asymptote) eurer Wahl.**

## Aufgabe 4.2N: Logistische Regression (NatWis)

**Datensatz [polis.csv](https://moodle.zhaw.ch/mod/resource/view.php?id=606624)**

Der Datensatz polis.csv beschreibt für 19 Inseln im Golf von Kalifornien, ob Eidechsen der Gattung Uta vorkommen (presence/absence: PA) in Abhängigkeit von der Form der Inseln (Verhältnis Umfang zu Fläche: RATIO). 

**Bitte prüft mit einer logistischen Regression, ob und ggf. wie die Inselform die Präsenz der Eidechsen beinflusst**

## Aufgabe 4.2S: Multiple logistische Regression (SozWis)

**Datensatz [Datensatz_novanimal_Uebung_Statistik4.2.csv](https://moodle.zhaw.ch/mod/resource/view.php?id=662344)**


Führt mit dem Datensatz der Gästebefragung eine logistische Regression durch. 
Kann der Mensabesuch durch die sozioökonomischen Variablen (Alter, Geschlecht, Hochschulzugehörigkeit), wahrgenommener Fleischkonsum und Umwelteinstellung vorhergesagt werden?


