---
date: 2022-10-31
lesson: Stat1
thema: Grundlagen der Statistik
index: 3
---

# Stat1: Übung

## Aufgabe 1.1: Assoziationstest

Führt einen Assoziationstest zweier kategorialer Variablen (mit je zwei Ausprägungen) mit Chi-Quadrat und Fishers exaktem Test durch. Dazu erhebt ihr selbst die Daten (wozu ihr euch auch in Teams zusammenschliessen könnt). Ihr könnt z.B. eine Datenerhebung unter Mitstudierenden durchführen (etwa Nutzung Mac/Windows vs. männlich/weiblich). Bitte formuliert vor der Datenerhebung eine Hypothese, d.h. eine Erwartungshaltung, ob und welche Assoziation vorliegt und wenn ja warum. Beachtet, dass ihr für diese Form des Assoziationstests genau zwei binäre Variablen benötigt. Wenn ihr also kategoriale Variablen mit mehr als zwei Ausprägungen habt, so könnt ihr entweder Ausprägungen sinnvoll zusammenfassen oder seltene Ausprägungen im Test unberücksichtigt lassen.

## Aufgabe 1.2: t-Test

**T-Test mit [Datensatz_novanimal_Uebung_Statistik1.2.csv](https://moodle.zhaw.ch/mod/resource/view.php?id=662330)**

Werden in den Basis- und Interventionswochen unterschiedlich viele Gerichte verkauft?

-   Schau die Daten an: Verstehen und ggf. plotten.
-   Definiere die Null- ($H_0$) und die Alternativhypothese ($H_1$).
-   Welche Form von t-Test musst Du anwenden: einseitig/zweiseitig resp. gepaart/ungepaart?
-   Führe einen t-Test durch.
-   Wie gut sind die Voraussetzungen für einen t-Test erfüllt (z.B. Normalverteilung der Residuen und Varianzhomogenität)?
-   Stelle deine Ergebnisse angemessen dar, d.h. Text mit Abbildung und/oder Tabelle
